site_name: Wiki
nav:
    - General: index.md
    - OData:
      - ODataCallRelated: OData.md
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'indigo'
    accent: 'indigo'